services:
  bs-frontend:
    image: bsfrontend
    ports:
      - 8000:3000
    volumes:
      - ./bsFrontend/src:/app/src
    depends_on:
      - bs-database
    build:
      context: ./bsFrontend

  bs-mean:
    image: bsmean
    volumes:
      - ./bsMean/src:/app/src
    depends_on:
      - bs-database
    build:
      context: ./bsMean

  bs-database:
    image: mongo
    restart: always
    command: --quiet --syslog
    expose:
      - 27017
    volumes:
      - bs-database:/data/db
      - mongo-config:/data/configdb

volumes:
  bs-database:
  mongo-config:
